### ISSUE TITLE
oracle 连接问题

### ISSUE THREAD

**Issue by MataSong** [ClickHouse/clickhouse-jdbc-bridge#139]
语法：
select *from jdbc('jdbc:oracle:thin:@:1521/服务?user=用户名&password=密码','库名','表名')

错误:
IO Error: NL Exception was generated.

铁铁，这个怎么解决呢？是插件的问题吗？

**Comment by zhicwu** [comment]
Not sure about this. What will you get from a JDBC client like DBeaver using the exact same connection string? Alternatively, besides checking network between oracle and jdbc bridge, you may consider to define the datasource in a configuration file so that you don't have to put user name and password in query.

Lastly, according to #96, it should work to run query like below:
```sql
select * from jdbc('jdbc:oracle:thin:test/123456@<ip address>:1521:orcl','select * from test.person')
```

**Comment by MataSong** [comment]
解决了，谢谢了。
