### ISSUE TITLE
Add docs about production ready connect clickhouse in docker with jdbc bridge

### ISSUE THREAD

**Issue by arturgspb** [ClickHouse/clickhouse-jdbc-bridge#23]

**Comment by zhicwu** [comment]
There's an all-in-one docker image simplified the installation,  as well as a separate docker image just for jobs bridge. You may refer to docker-compose file as example to set up the environment. 

As to production readiness,  I'm afraid it's not fully ready yet and we need to wait until connection timeout issue fixed in clickhouse server.
